apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    run: {{ .Values.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    run: {{ .Values.service.name }}
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: config
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http