deployment:
  name: open-imis-backend
  spec:
    name: open-imis
  containers:
    name: open-imis-backend
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/open-imis/dev-backend:latest
    imagePullPolicy: "Always"