deployment:
  name: backend
  containers:
    name: open-imis-backend
    image: oleksiidn/open-imis-backend:0.0.8
    imagePullPolicy: "Always"
    port: 8000

service:
  name: backend
  port: 8000
  type: ClusterIP
  targetPort: 8000
