version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.2.0
  helm: circleci/helm@1.0
  kubernetes: circleci/kubernetes@1.3.1

workflows:
  Deploy OpenIMIS to EKS cluster:
    jobs:
      #      - hold:
      #          type: approval
      - deploy-open-imis:
          context: aws
#          requires:
#            - hold

jobs:
  deploy-open-imis:
    environment:
      AWS_REGION: eu-west-1
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - aws-cli/setup:
          role-arn: "arn:aws:iam::463471358064:role/CICDPipeline_sandbox-bb-payments_Role_dev"
          aws-region: eu-west-1
#          profile-name: ${AWS_ROLE}
#          role-session-name: CircleSession
#          session-duration: '1800'
#      - aws-eks/update-kubeconfig-with-authenticator:
#          cluster-name: "${AWS_CLUSTER_NAME}"
#          cluster-authentication-role-arn: arn:aws:iam::${AWS_ACCOUNT}:role/${AWS_ROLE}
#      - run:
#          name: Install chart
#          command: |
#            helm dependency update ./sandbox-open-imis
#            helm upgrade --install sandbox-open-imis ./sandbox-open-imis --create-namespace --namespace open-imis

      - run:
          name: Log-into-AWS-ECR
          command: |
            # must use same profile specified in the step above
            aws ecr get-login-password --profile "OIDC-PROFILE"