# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-eks: circleci/aws-eks@2.1.2
  helm: circleci/helm@1.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
#  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
  deploy-project:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: arn:aws:iam::463471358064:role/CircleCIRole
          aws-region: AWS_REGION
          profile-name: CircleCIRole
          role-session-name: CircleSession
          session-duration: '1800'
#      - aws-eks/update-kubeconfig-with-authenticator:
#          cluster-name: 'Govstack-sandbox-cluster-dev'
#          aws-region: 'eu-west-1'

      - helm/install-helm-client:
          version: v3.2.0
      - run:
          name: Update kubectl
          command: |
            aws eks update-kubeconfig --region eu-central-1 --name Govstack-sandbox-cluster-dev --role-arn arn:aws:iam::463471358064:role/CircleCIRole
      - run:
          name: Install chart
          command: |
            helm dependency update ./sandbox-open-imis
            helm upgrade --install sandbox-open-imis ./sandbox-open-imis/ -f val.yaml 

workflows:
  Deploy project to DEV environment:
    jobs:
#      - say-hello
#      - hold:
#          type: approval
      - deploy-project:
          context: aws
#          requires:
#            - hold
