apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.global.name }}
  clusterIP: None