apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.deployment.spec.name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.deployment.spec.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.containers.name }}
          image: {{ .Values.deployment.containers.image }}
          imagePullPolicy: {{ .Values.deployment.containers.imagePullPolicy }}