apiVersion: v1
kind: Service
metadata:
  name: open-imis-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: open-imis-db
spec:
  ports:
    - port: 5432
  selector:
    app: open-imis
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  dbSnapshotIdentifier: {{ .Values.db.spec.dbSnapshotIdentifier }}
  dbInstanceIdentifier: {{ .Values.db.name }}
  engine: postgres
  masterUsername: {{ .Values.db.spec.masterUsername }}
  masterUserPassword:
    namespace: {{ .Values.global.namespace }}
    name: {{ .Values.secret.name }}
    key: password
  dbSubnetGroupName: default
  dbInstanceClass: db.t4g.micro
  allocatedStorage: 20
  deletionProtection: false