apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: open-imis-db
  namespace: {{ .Values.global.namespace }}
spec:
  dbSnapshotIdentifier: "arn:aws:rds:eu-central-1:463471358064:snapshot:open-imis-snapshot"
  dbInstanceIdentifier: open-imis-db
  engine: postgres
  masterUsername: "IMISuser"
  masterUserPassword:
    namespace: {{ .Values.global.namespace }}
    name: "open-imis-secret"
    key: password
  dbSubnetGroupName: default
  dbInstanceClass: db.t4g.micro
  allocatedStorage: 20
  deletionProtection: false